### ISSUE TITLE
failure to install mirror-core

### ISSUE THREAD

**Issue by cartazio** [coq/opam-coq-archive#172]
```
$ opam install coq-mirror-core
The following actions will be performed:
  ∗  install coq-ext-lib      0.9.5           [required by coq-mirror-core]
  ∗  install coq-plugin-utils 1.1.0           [required by coq-mirror-core]
  ∗  install coq-mirror-core  1.0.2
```

the error message was 
```

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed coq-ext-lib.0.9.5
[ERROR] The compilation of coq-plugin-utils failed at "make -j1".
Processing  2/3: [coq-plugin-utils: rm]
#=== ERROR while installing coq-plugin-utils.1.1.0 ============================#
# opam-version 1.2.2
# os           darwin
# command      make -j1
# path         /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0
# compiler     system (4.05.0)
# exit-code    2
# env-file     /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0/coq-plugin-utils-45157-335865.env
# stdout-file  /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0/coq-plugin-utils-45157-335865.out
# stderr-file  /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0/coq-plugin-utils-45157-335865.err
### stdout ###
# [...]
# CAMLDEP src/term_match.mli
# CAMLDEP src/coqstd.mli
# COQDEP src/plugin_utils.mlpack
# CAMLDEP src/use_ltac.ml
# CAMLDEP src/term_match.ml
# CAMLDEP src/coqstd.ml
# CAMLDEP -pp src/plugin_utils_plugin.ml4
# COQDEP theories/PluginUtils.v
# CAMLC -c src/use_ltac.mli
# CAMLC -c src/use_ltac.ml
### stderr ###
# File "src/use_ltac.ml", line 16, characters 20-38:
# Error: Unbound constructor Tacexpr.TacDynamic
# make[1]: *** [src/use_ltac.cmo] Error 2
# make: *** [plugin] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions were aborted
  ∗  install coq-mirror-core 1.0.2
The following actions failed
  ∗  install coq-plugin-utils 1.1.0
The following changes have been performed
  ∗  install coq-ext-lib 0.9.5

The former state can be restored with:
    opam switch import "~/.opam/system/backup/state-20170625203344.export"
```

**Comment by gares** [comment]
Hum I wonder why opam is trying to install coq-plugin-utils 1.1.0 instead of 1.2.0.
The problem is that 1.1.0 has a loose specification of the supported Coq version (I guess you are on 8.6), while 1.2.0 is more precise (and supports both 8.5 and 8.6 as far as I know).
Could you please run `opam update` and retry. If it does not work, could you please try `opam install coq-plugin-utils.1.1.0`?

**Comment by cartazio** [comment]
both failed 

```
$ opam install coq-mirror-core
The following actions will be performed:
  ∗  install coq-plugin-utils 1.1.0           [required by coq-mirror-core]
  ∗  install coq-mirror-core  1.0.2
===== ∗  2 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[coq-mirror-core] Archive in cache
[coq-plugin-utils] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of coq-plugin-utils failed at "make -j1".
Processing  1/2: [coq-plugin-utils: rm]
#=== ERROR while installing coq-plugin-utils.1.1.0 ============================#
# opam-version 1.2.2
# os           darwin
# command      make -j1
# path         /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0
# compiler     system (4.05.0)
# exit-code    2
# env-file     /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0/coq-plugin-utils-58674-e7966f.env
# stdout-file  /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0/coq-plugin-utils-58674-e7966f.out
# stderr-file  /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0/coq-plugin-utils-58674-e7966f.err
### stdout ###
# [...]
# CAMLDEP src/term_match.mli
# CAMLDEP src/coqstd.mli
# COQDEP src/plugin_utils.mlpack
# CAMLDEP src/use_ltac.ml
# CAMLDEP src/term_match.ml
# CAMLDEP src/coqstd.ml
# CAMLDEP -pp src/plugin_utils_plugin.ml4
# COQDEP theories/PluginUtils.v
# CAMLC -c src/use_ltac.mli
# CAMLC -c src/use_ltac.ml
### stderr ###
# File "src/use_ltac.ml", line 16, characters 20-38:
# Error: Unbound constructor Tacexpr.TacDynamic
# make[1]: *** [src/use_ltac.cmo] Error 2
# make: *** [plugin] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions were aborted
  ∗  install coq-mirror-core 1.0.2
The following actions failed
  ∗  install coq-plugin-utils 1.1.0
No changes have been performed
16:36:14 ~/W/p/a/resin (master↑1|✔) $ opam install coq-plugin-utils.1.1.0
The following actions will be performed:
  ∗  install coq-plugin-utils 1.1.0

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[coq-plugin-utils] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of coq-plugin-utils failed at "make -j1".
Processing  1/1: [coq-plugin-utils: rm]
#=== ERROR while installing coq-plugin-utils.1.1.0 ============================#
# opam-version 1.2.2
# os           darwin
# command      make -j1
# path         /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0
# compiler     system (4.05.0)
# exit-code    2
# env-file     /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0/coq-plugin-utils-58800-6d07ae.env
# stdout-file  /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0/coq-plugin-utils-58800-6d07ae.out
# stderr-file  /Users/carter/.opam/system/build/coq-plugin-utils.1.1.0/coq-plugin-utils-58800-6d07ae.err
### stdout ###
# [...]
# CAMLDEP src/term_match.mli
# CAMLDEP src/coqstd.mli
# COQDEP src/plugin_utils.mlpack
# CAMLDEP src/use_ltac.ml
# CAMLDEP src/term_match.ml
# CAMLDEP src/coqstd.ml
# CAMLDEP -pp src/plugin_utils_plugin.ml4
# COQDEP theories/PluginUtils.v
# CAMLC -c src/use_ltac.mli
# CAMLC -c src/use_ltac.ml
### stderr ###
# File "src/use_ltac.ml", line 16, characters 20-38:
# Error: Unbound constructor Tacexpr.TacDynamic
# make[1]: *** [src/use_ltac.cmo] Error 2
# make: *** [plugin] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install coq-plugin-utils 1.1.0
No changes have been performed
```

per se theres no release that supports 8.6?

**Comment by silene** [comment]
I think @gares made a typo and meant to suggest trying `opam install coq-plugin-utils=1.2.0 coq-mirror-core` to force `opam` to install the latest version of `plugin-utils`. That said, even this latest version does not seem to be compatible with 8.6, but perhaps @gmalecha knows more about this.

**Comment by mattam82** [comment]
@gmalecha ping? coq-plugin-utils needs version 1.3.0 to build on 8.6, 1.2.0 had incorrect dependencies, I'll fix that. AFAIU mirror-core has no 8.6 release yet.

**Comment by gmalecha** [comment]
I haven't been able to port the mirror-core plugin to 8.6 yet, which is why there is not currently a release for it. @cartazio I've made an issue on the mirror-core repository for this: https://github.com/gmalecha/mirror-core/issues/104 .

**Comment by gmalecha** [comment]
Thanks @mattam82 for fixing the plugin-utils dependencies.

**Comment by clarus** [comment]
The command `opam install coq-plugin-utils.1.1.0` now refuses to install on Coq 8.6 with the following message:
```
~€ opam list
# Packages matching: installed
# Name              # Installed       # Synopsis
base-bigarray       base
base-num            base              Num library distributed with the OCaml compiler
base-threads        base
base-unix           base
camlp5              7.06.10-g84ce6cc4 Preprocessor-pretty-printer of OCaml
conf-m4             1                 Virtual package relying on m4
coq                 8.6               pinned to version 8.6
num                 0                 The Num library for arbitrary-precision integer and rational arithmetic
ocaml               4.05.0            The OCaml compiler (virtual package)
ocaml-base-compiler 4.05.0            Official 4.05.0 release
ocaml-config        1                 OCaml Switch Configuration
ocamlfind           1.8.0             A library manager for OCaml
~€ opam install coq-plugin-utils.1.1.0
The following dependencies couldn't be met:
  - coq-plugin-utils → coq < 8.6~
      not available because the package is pinned to version 8.6

No solution found, exiting
```
and `opam install coq-plugin-utils` works:
```
~€ opam install coq-plugin-utils
The following actions will be performed:
  ∗ install coq-plugin-utils 1.3.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[coq-plugin-utils.1.3.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed coq-plugin-utils.1.3.0
Done.
```

@cartazio Do you confirm I can close this issue (or that you do not care anymore :))?

**Comment by clarus** [comment]
Closing this issue as this seems fixed.
