### PR TITLE
Release CoqHammer 1.3.1

### PR DESCRIPTION
**Pull request by anton-trunov**
Related issue: https://github.com/lukaszcz/coqhammer/issues/103

CC @lukaszcz @palmskog

### CODE REVIEW

**Comment by anton-trunov** [comment]
@clarus I'm wondering if I should constraint the OCaml version here. (E.g. CoqHammer 1.3 does not do it in the `depends` section of the opam files but only in the `build` section). Or is it fine to merge it as is since the build seems to fail on 4.05 and that is unsupported, afaict.

**Comment by lukaszcz** [comment]
With earlier ocaml versions you just need the stdlib-shims library to
build. I haven't invested time yet to figure out how to properly handle
this in opam

**Comment by clarus** [comment]
For `coq-hammer-tactics.1.3.1+8.13` the error may be from the `install` rule rather than `build`? I do not really get what should happen for unsupported OCaml versions. The solution may be to constraint the OCaml version in the dependencies then. I think it is better that opam knows the unsupported versions, so that it can suggest to the user to upgrade.

**Comment by anton-trunov** [comment]
> With earlier ocaml versions you just need the stdlib-shims library to build.

@lukaszcz I tried fixing this with the following line in dependencies:

```
(("ocaml" { < "4.08" } & "stdlib-shims") | ("ocaml" { >= "4.08" }))
```

but the build system does not mention `stdlib-shims`, afaict, so this fails.

**Comment by lukaszcz** [comment]
> but the build system does not mention stdlib-shims, afaict, so this fails.

I'm confused. You mean CoqHammer's build system? Of course it doesn't,
stdlib-shims is a dependency which is supposed to be preinstalled; it's
available via opam (https://opam.ocaml.org/packages/stdlib-shims/).

**Comment by anton-trunov** [comment]
> Of course it doesn't,
stdlib-shims is a dependency which is supposed to be preinstalled; 

I tried replicating the build with OCaml 4.05.0 locally.
I installed `stdlib-shims` and ran `make tactics` but I got the following error:
```
CAMLOPT -c -for-pack Hammer_lib src/lib/hhlib.ml
File "src/lib/hhlib.ml", line 79, characters 19-33:
Error: Unbound module Stdlib
make[2]: *** [src/lib/hhlib.cmx] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

**Comment by lukaszcz** [comment]
You're right. With Ocaml 4.07.1 stdlib-shims somehow works out-of-the-box
just by installing it with opam, but I tried OCaml 4.05 and it doesn't
work. I'll try to fix this soon.

**Comment by lukaszcz** [comment]
I give up. I don't know how to make stdlib-shims work with OCaml 4.05 and
Coq plugins. Apparently, when you install stdlib-shims via opam then the
bytecode version of the library is not included, but it is then needed by
Coq for some reason. The build fails and I don't know how to fix this.

I suggest just making OCaml >= 4.08 a dependency.

**Comment by clarus** [comment]
OK, I allowed myself to add a commit to add the OCaml >= 4.08 dependency.

**Comment by anton-trunov** [comment]
@clarus Thanks a lot! I was going to try and add conditional dependencies but the last week turned out to be quite busy. We could probably add an issue for CoqHammer to do that eventually.
