### PR TITLE
The 8.6.dev branch of equations works with any Coq 8.6 version

### PR DESCRIPTION
**Pull request by mattam82**

### CODE REVIEW

**Comment by gares** [comment]
Compilation failed...could you please check the logs?

**Comment by mattam82** [comment]
That one seems to be due to an unexpected change in ocaml, I'll investigate

**Comment by gares** [comment]
The travis scripts finally work, I'll close/open the PR to pick up the fixes
